databases:
  - name: terminus
    plan: free
    databaseName: terminus
    postgresMajorVersion: 18
    user: terminus
    ipAllowList: []

services:
  - type: web
    name: terminus-web
    plan: free
    autoDeployTrigger: commit
    healthCheckPath: /up
    runtime: docker
    envVars:
      - key: API_URI
        fromService:
          type: web
          name: terminus-web
          property: host
      - key: APP_SETUP
        value: true
      - key: HANAMI_PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: terminus
          property: connectionString
      - key: KEYVALUE_URL
        fromService:
          type: keyvalue
          name: terminus-keyvalue
          property: connectionString

  - type: worker
    name: terminus-worker
    plan: starter
    autoDeployTrigger: commit
    runtime: docker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: terminus
          property: connectionString
      - key: KEYVALUE_URL
        fromService:
          type: keyvalue
          name: terminus-keyvalue
          property: connectionString
    dockerCommand: bundle exec sidekiq -r ./config/sidekiq.rb

  - type: keyvalue
    name: terminus-keyvalue
    plan: free
    ipAllowList: []
